# Generated by Django 4.0.1 on 2022-02-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_askstor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobstor',
            fields=[
                ('by', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('time', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Newstor',
            fields=[
                ('by', models.CharField(max_length=200)),
                ('descendants', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=200)),
                ('time', models.IntegerField(default=None)),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=200)),
                ('url', models.CharField(default=None, max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Showstor',
            fields=[
                ('by', models.CharField(max_length=200)),
                ('descendants', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('text', models.TextField()),
                ('time', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Askstoris',
        # ),
    ]
